name: Secret Update Reminder

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install PyGithub

      - name: Create GitHub App Token
        id: create_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run secret check and alert script
        run: python .github/scripts/check_and_alert_secret.py
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
